name: Greeting on variable day
on:
  workflow_dispatch
env:
  DAY_OF_WEEK: Wednesday

jobs:
  greeting_job:
    runs-on: ubuntu-24.04-arm
    env:
      Gretting: Hello
    steps:
      - name: say hello
        run: echo "$Gretting $First_name. Today is $DAY_OF_WEEK"
        env:
          First_name: Ram    
      
